
(async()=>{const root=document.getElementById('app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let D;try{D=await fetch('curriculo.json',{cache:'no-store'}).then(r=>r.json())}catch(e){root.innerHTML='Erro ao carregar.';return}
const all=D.disciplinas,req=all.filter(x=>x.tipo!=='Optativa'),opt=all.filter(x=>x.tipo==='Optativa'),by=Object.fromEntries(all.map(x=>[x.codigo,x])),K='bio_curriculo_v1';let done=new Set(JSON.parse(localStorage.getItem(K)||'[]')),query='',filter='Todos';
const unlocked=x=>x.preRequisitos.every(c=>done.has(c)), unlocks=c=>all.filter(x=>x.preRequisitos.includes(c)).map(x=>x.codigo);
function card(x){return `<article class="course ${done.has(x.codigo)?'done':''} ${!done.has(x.codigo)&&!unlocked(x)?'locked':''}"><div class="head"><span class="code">${esc(x.codigo)}</span><span class="badge">${esc(x.tipo)}</span></div><h3>${esc(x.nome)}</h3><div class="meta">${x.cargaHoraria} h · ${esc(x.departamento)} · ${done.has(x.codigo)?'Concluída':unlocked(x)?'Disponível':'Bloqueada'}</div><div class="pre"><b>Pré-requisitos:</b> ${x.preRequisitos.length?esc(x.preRequisitos.join(' + ')):'Sem pré-requisito'}</div><div class="faculty">${(x.docentes||[]).length?`<b>Docente${x.docentes.length>1?'s':''}:</b> `+(x.docentes||[]).map(d=>d.lattes?`<a href="${esc(d.lattes)}" target="_blank" rel="noopener">${esc(d.nome)}</a>`:esc(d.nome)).join(' · '):''}</div><div class="actions"><a href="${esc(x.ficha1)}" target="_blank">Ficha 1 / ementa</a><button class="map-btn" data-c="${x.codigo}">Mapa</button><button class="done-btn" data-c="${x.codigo}">${done.has(x.codigo)?'Desmarcar':'Marcar concluída'}</button></div></article>`}
root.innerHTML=`<section class="hero"><div class="eyebrow">UFPR · BIOMEDICINA · ${D.version}</div><h1>${D.title}</h1><p>${D.subtitle}</p></section>
<section class="home-intro">${esc(D.home?.intro||'')}</section>
<section class="home-links">
${Object.entries((D.home?.quickLinks||[]).reduce((acc,l)=>{(acc[l.group]??=[]).push(l);return acc},{})).map(([g,ls])=>`
<article class="home-group"><h2>${esc(g)}</h2><div class="home-group-links">${ls.map(l=>`<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.label)}</a>`).join('')}</div></article>`).join('')}
</section>
<section class="home-notices">
${(D.home?.notices||[]).filter(n=>n.active!==false).map(n=>`<article class="home-notice"><b>${esc(n.title)}</b><span>${esc(n.text)}</span></article>`).join('')}
</section>
<div class="metrics">${[['Períodos',D.summary.periodos],['Carga total',D.summary.cargaTotal+' h'],['Obrigatórias',D.summary.obrigatoriasHoras+' h'],['Optativas exigidas',D.summary.optativasHorasExigidas+' h'],['Ativ. formativas',D.summary.atividadesFormativasHoras+' h'],['Extensão',D.summary.extensaoCurricularizadaHoras+' h']].map(a=>`<div class="metric"><small>${a[0]}</small><strong>${a[1]}</strong></div>`).join('')}</div><section class="panel"><div><b>Meu percurso curricular</b> · <span id="pt"></span></div><div class="bar"><div id="pb"></div></div><div id="pd" class="meta"></div><div class="actions"><button id="clear">Limpar progresso</button></div></section><div class="controls"><input id="q" class="search" placeholder="Buscar código, disciplina ou departamento"><div class="filters">${['Todos','Obrigatórias','Optativas','Disponíveis','Bloqueadas','Concluídas'].map((x,i)=>`<button class="filter ${i?'':'active'}" data-f="${x}">${x}</button>`).join('')}</div></div><section class="section"><h2>Mapa de pré-requisitos</h2><div id="map" class="mapbox">Selecione “Mapa” em uma disciplina.</div></section><section class="section"><h2>8 períodos</h2><div id="sem"></div></section><section class="section"><h2>Optativas — 51 disciplinas</h2><div id="opts" class="opt-grid"></div></section><section class="section"><div class="notice">${D.notes.join(' · ')}</div></section><section class="section"><h2>Fontes</h2><div class="panel sources">${D.sourceLinks.map(l=>`<a href="${l.url}" target="_blank">${l.label}</a>`).join('')}</div></section>`;
function match(x){let s=query.toLowerCase(),ok=!s||[x.codigo,x.nome,x.departamento,...x.preRequisitos].join(' ').toLowerCase().includes(s);if(filter==='Obrigatórias')ok&=x.tipo!=='Optativa';if(filter==='Optativas')ok&=x.tipo==='Optativa';if(filter==='Disponíveis')ok&=!done.has(x.codigo)&&unlocked(x);if(filter==='Bloqueadas')ok&=!done.has(x.codigo)&&!unlocked(x);if(filter==='Concluídas')ok&=done.has(x.codigo);return !!ok}
function prog(){let rh=req.filter(x=>done.has(x.codigo)).reduce((a,x)=>a+x.cargaHoraria,0),oh=opt.filter(x=>done.has(x.codigo)).reduce((a,x)=>a+x.cargaHoraria,0),cred=rh+Math.min(oh,D.summary.optativasHorasExigidas),den=D.summary.obrigatoriasHoras+D.summary.optativasHorasExigidas,p=Math.round(cred/den*100);pt.textContent=p+'%';pb.style.width=p+'%';pd.textContent=`Obrigatórias: ${rh}/${D.summary.obrigatoriasHoras} h · Optativas marcadas: ${oh} h (exigidas ${D.summary.optativasHorasExigidas} h).`}
function bind(){document.querySelectorAll('.done-btn').forEach(b=>b.onclick=()=>{done.has(b.dataset.c)?done.delete(b.dataset.c):done.add(b.dataset.c);localStorage.setItem(K,JSON.stringify([...done]));render()});document.querySelectorAll('.map-btn').forEach(b=>b.onclick=()=>{let x=by[b.dataset.c],u=unlocks(x.codigo);map.innerHTML=`<b>${x.codigo} · ${esc(x.nome)}</b><div class="chain">${x.preRequisitos.map(c=>`<span class="node">${c}</span>`).join('')}<span class="node target">${x.codigo}</span>${u.map(c=>`<span class="node">${c}</span>`).join('')}</div><div class="meta">Desbloqueia diretamente: ${u.length?u.join(', '):'nenhuma'}.</div>`})}
function render(){sem.innerHTML=[1,2,3,4,5,6,7,8].map(p=>{let a=req.filter(x=>x.periodo===p&&match(x)),t=req.filter(x=>x.periodo===p).reduce((s,x)=>s+x.cargaHoraria,0);return `<details class="semester" ${p<3?'open':''}><summary><span>${p}º período</span><span>${t} h</span></summary><div class="courses">${a.map(card).join('')||'<div class="empty">Sem resultados</div>'}</div></details>`}).join('');let o=opt.filter(match);opts.innerHTML=o.map(card).join('')||'<div class="empty">Sem resultados</div>';prog();bind()}
q.oninput=()=>{query=q.value;render()};document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.f;render()});clear.onclick=()=>{done.clear();localStorage.removeItem(K);render()};render()})();
